; AN ARRAY M WITH N WORD-DATA HAS BEEN DEFINED IN THE DATA SEGMENT, TRY TO FIND 
; THE LARGEST ABSOLUTE FIGURE AMONG THESE FIGURES, PUT IT IN THE (M+2N) UNIT OF 
; DATA SEGMENT,AND OFFSET THE NUMBER ADRRESS SHOULD BE STORED IN (M+2(N+1)) UNIT.

DATA	SEGMENT
MEM		DW	4 DUP(-2),0,0,4 DUP(1)
MAX		DW	0
ADDRE	DW	0
TEM		DW	10 DUP(0)
DATA	ENDS

CODE	SEGMENT
ASSUME	CS:CODE,DS:DATA
START:	MOV AX,DATA
		MOV DS,AX
		MOV CX,10 
		LEA SI,MEM
		LEA DI,TEM
		
NEXT:	MOV AX,[SI]			; CONVERT ALL FIGURES TO POSITIVE
		CMP AX,0
		JG LARGER
		NEG AX
LARGER:	MOV [DI],AX
		ADD SI,2
		ADD DI,2
		LOOP NEXT
							; FIND THE LARGEST FIGURE AND STORE THE OFFSET ADDRESS
		MOV CX,10 
		LEA DI,TEM  
		MOV BX,[DI]
		MOV ADDRE,DI
FIND_MAX: CMP BX,[DI]
		JG GREAT
		MOV BX,[DI]
		MOV ADDRE,DI
GREAT:	ADD DI,2
		LOOP FIND_MAX
		 
		SUB ADDRE,24 
		MOV MAX,BX
		HLT
CODE	ENDS
		END START