; THERE IS A 16-BIT FIGURE IN AX, DIVIDE IT INTO 4 PARTS, THEN STORE THEM AS FOLLOW:
; |   AL   |   BL   |  CL    |   DL   |
; |0000AX00|0000AX01|0000AX10|0000AX11|

CODE	SEGMENT
ASSUME	CS:CODE
START:	MOV AX,0D9BDH	; AX=D9BD
		MOV BX,AX		; BACKUP IN BX
		MOV CL,4		; SET A 4 TIMES COUNTER
		MOV DX,AX		; BACKUP IN DX
		MOV AL,AH		; MOVE D9H TO AL
		SHR AL,CL		; SHIFT AL TO RIGHT WITH 4 BITS TO GET 0DH IN AL
		MOV BL,BH		; MOVE D9H TO BL
		AND BL,0FH		; SAVE THE LAST 4 BITS TO GET 09H IN BL
		MOV DH,DL		; MOVE BDH TO DH
		SHR DH,CL		; SHIFT DH TO RIGHT WITH 4 BITS TO GET 0BH IN DH
		MOV CL,DH		; MOVE 0BH TO CL
		AND DL,0FH		; SAVE THE LAST 4 BITS WHICH IS 0DH IN DL
CODE	ENDS
		END START