; INPUT SEVERAL CHARACTERS WITH KEYBOARD ENDING WITH ENTER, THEN DIVIDE THEM INTO CHARACTERS 
; NUMBERS AND  OTHERS AND OUTPUT THEIR NUMBERS.

DATA	SEGMENT
CHAR	DB	0
NUM		DB	0
OTHER	DB	0  
RES_C   DB  'CHARECTAERS: $'
RES_N   DB  'NUMBERS: $'
RES_O   DB  'OTHERS: $'
DATA	ENDS

CODE	SEGMENT
ASSUME	CS:CODE,DS:DATA
START:	MOV AX,DATA
		MOV DS,AX
INPUT:	MOV AH,1
		INT 21H				; INPUT FROM KEYBOARD
		CMP AL,0DH			; ASCII(ENTER)=0DH, COMPARE INPUT WITH ENTER
		JZ	DISP			; YES, JUMP TO DISP TO OUTPUT THE RESULTS
		CMP AL,30H			; ASCII(0)=30H
		JB	OTHERS			; IF INPUT IS LESS THAN 30H IT MEANS IT BELONGS TO OTHERS
		CMP AL,39H			; ASCII(9)=39H
		JBE NUMBERS			; YES, JUMP TO NUMBERS TO COUNT
		CMP AL,41H			; ASCII(A)=41H
		JB	OTHERS			; LESS THAN 'A' MEANS IT BELONGS TO OTHERS
		CMP AL,5AH			; ASCII(Z)=5AH
		JBE CHARACTERS		; YES, JUMP TO CHARACTERS TO COUNT
		CMP AL,61H			; ASCII(a)=61H
		JB	OTHERS			; LESS THAN 'a' MEANS IT BELONGS TO OTHERS
		CMP AL,7AH			; ASCII(z)=7AH
		JBE	CHARACTERS		; YES, JUMP TO CHARACTERS TO COUNT
OTHERS:	INC OTHER 			; OR GREAT THAN 'z' MEANS THAT IT BELONGS TO OTHERS, COUNT
		JMP	INPUT
NUMBERS: INC NUM
		JMP INPUT
CHARACTERS: INC CHAR
		JMP INPUT
		
DISP:   MOV AH,2
        MOV DL,0AH
        INT 21H
        MOV AH,2		
        MOV DL,0DH
        INT 21H   
		
        MOV AH,09H			; DISPLAY THE NUMBER OF CHAR
        MOV DX,OFFSET RES_C
        INT 21H
        MOV AH,2
        MOV DL,CHAR
        OR  DL,30H			; TURN NUMBER TO 'NUMBER', SUCH AS 1 -> '1'
        INT 21H          

        MOV AH,09H			; DISPLAY THE NUMBER OF NUM
        MOV DX,OFFSET RES_N
        INT 21H
        MOV AH,2
        MOV DL,NUM
        OR  DL,30H
        INT 21H         
 
        MOV AH,09H			; DISPLAY THE NUMBER OF OTHER
        MOV DX,OFFSET RES_O
        INT 21H
        MOV AH,2
        MOV DL,OTHER
        OR  DL,30H
        INT 21H		
		HLT
CODE	ENDS
		END START