; THERE IS A STRING (BYTE) WITH SEVERAL CHARACTERS IN 'STRING', TRY TO DELETE NUMBERS AND SPACES 
; ON BOTH SIDES OF THE STRING.

DATA	SEGMENT
STRING	DB	' 1234HELLO 1234$'
LEN		EQU	$-STRING
TEM		DB	50 DUP(0)
DATA	ENDS

CODE	SEGMENT
ASSUME	CS:CODE,DS:DATA
START:	MOV AX,DATA
		MOV DS,AX 
		MOV AX,0
		MOV CX,LEN
		LEA SI,STRING
		LEA DI,TEM
		
RECONG:	MOV AL,[SI]
		CMP AL,20H
		JZ	SKIP 
		CMP AL,30H
		JL	STORE
		CMP AL,39H
		JLE	SKIP
STORE:	MOV [DI],AX
		INC DI
SKIP:	INC SI
		LOOP RECONG
		
		LEA SI,STRING
		LEA DI,TEM
		MOV CX,LEN
RESTORE: MOV AL,[DI]
		MOV [SI],AL
		INC DI
		INC SI
		LOOP RESTORE
		MOV AH,4CH
		INT 21H
CODE	ENDS
		END START