; EXTRACT FROM <THE PRINCIPLE OF MICROCOMPUTER> TEXTBOOK.
; IF DL STORES ODD NUMBER, SET AL 0, OTHERWISE SET AL -1

CODE	SEGMENT
ASSUME	CS:CODE
START:	MOV DL,01H
        TEST DL,01H	; TEST WILL 'AND' TWO OPRAS BIT TO BIT, AND THE 
					; LAST BIT OF ODD NUMBER IS 1, 'AND' 01H EQUALS 
					; TO 01H(!=0) WHICH MEANS ZF=0, THEN JUMP TO NEXT
		JNZ NEXT
		MOV	AL,-1	; IF DL 'AND' 01H EQUALS TO ZERO, ZF=1, SET AL -1
		HLT
NEXT:	MOV	AL,0
CODE	ENDS
		END	START