; SUBSTRATE 1 FROM 256 MEMORY CELLS BEGINNING AT 1A000H, AND THE LOOP ENDS WHEN ANY ELEMENT BECOMES ZERO.

CODE	SEGMENT
ASSUME	CS:CODE
START:	MOV	AX,1A00H
		MOV	DS,AX			; SET DS 1A00H SO THAT DS*16=1A000H
		MOV	CX,256			; SET A 256 TIMES COUNTER
		MOV	DI,0			; SET BEGIN POSITION
GOON:	DEC	BYTE PTR[DI]	; ELEMENT[0] SUBSTRATE 1
		INC	DI				; MOVE POINTER TO THE NEXT ELEMENT[1]
		CMP	BYTE PTR[DI-1],0; COMPARE ELEMENT[0] AND ZERO
		LOOPNZ	GOON		; IF ELEMENT EQUALS TO ZERO QUIT LOOP
CODE	ENDS
		END	START