; THERE ARE 100 NUMBERS IN MEM, DELETE ALL THE ZERO AND MERGE THESE EMPTY TABLES 
; WITH THE NEXT NUMBERS(NOT ZERO).

DATA	SEGMENT
MEM		DW	25 DUP(1,0,1,0)	; DEFINE A WORD ARRAY WITH 100 NUMBERS
TEM		DW	100 DUP(0)		; DEFINE A TEM ARRAY
DATA	ENDS

CODE	SEGMENT
ASSUME	CS:CODE,DS:DATA
START:	MOV AX,DATA
		MOV DS,AX
		LEA SI,MEM
		LEA DI,TEM
		MOV BX,0
		MOV CX,100
							; STORE ALL THE NON-ZERO FIGURES IN TEM ARRAY
NEXT:	CMP [SI],0	
		JZ	ZERO
		MOV BX,[SI]
		MOV [DI],BX
		INC DI
		INC DI
ZERO:	INC SI
		INC SI
		LOOP NEXT
							; MOVE THESE FIGURES BACK
		MOV CX,100  
		MOV BX,0
		LEA SI,MEM
		LEA DI,TEM  
AGAIN:  MOV BX,[DI]
        MOV [SI],BX
        ADD SI,2
        ADD DI,2
        LOOP AGAIN
        HLT
CODE	ENDS
		END START