; ALLOCATE THE GRADES OF 12 STUDENTS TO SIX SECTIONS: <60, 60-69, 70-79, 80-89, 90-99, 100

DATA	SEGMENT
TABLE	DB	76,69,82,90,54,42,59,68,71,86,91,100	; STORE GRADES OF TWELVE STUDENTS
S10		DB	(0)				; STORE THE NUMBER OF STUDENTS WHOSE GRADE IS 100
S9		DB	(0)				; STORE THE NUMBER OF STUDENTS WHOSE GRADE IS BETWEEN 90 TO 99
S8		DB	(0)				; STORE THE NUMBER OF STUDENTS WHOSE GRADE IS BETWEEN 80 TO 89
S7		DB	(0)				; STORE THE NUMBER OF STUDENTS WHOSE GRADE IS BETWEEN 70 TO 79
S6		DB	(0)				; STORE THE NUMBER OF STUDENTS WHOSE GRADE IS BETWEEN 60 TO 69
S5		DB	(0)  			; STORE THE NUMBER OF STUDENTS WHOSE GRADE IS BELOW 60
LEN		EQU S10-TABLE		; THE QUANTITY OF STUDENTS
DATA	ENDS

CODE	SEGMENT
ASSUME	DS:DATA,CS:CODE
START:	MOV AX,DATA
		MOV DS,AX
		MOV CX,LEN
		LEA SI,TABLE		; GET THE START ADDRESS OF TABLE
NEXT:	MOV AL,[SI]			; MOVE THE FIRST GRADE TO AL
		CMP AL,59			; COMPARE WITH 59
		JNA AGAIN1			; IF GRADE IS NOT ABOVE 59 JUMP TO AGAIN1
		CMP AL,69         	; 60-69?
		JNA AGAIN2
		CMP AL,79			; 70-79?
		JNA AGAIN3
		CMP AL,89			; 80-89?
		JNA AGAIN4
		CMP AL,99			; 90-99?
		JNA AGAIN5
		CMP AL,100			; 100?
		JNA AGAIN6
		
AGAIN1:	INC S5
		INC SI
		DEC CX
		JNZ NEXT
		HLT
AGAIN2:	INC S6
		INC SI
		DEC CX
		JNZ NEXT
		HLT
AGAIN3:	INC S7
		INC SI
		DEC CX
		JNZ NEXT
		HLT
AGAIN4:	INC S8
		INC SI
		DEC CX
		JNZ NEXT
		HLT
AGAIN5:	INC S9
		INC SI
		DEC CX
		JNZ NEXT
		HLT
AGAIN6:	INC S10
		INC SI
		DEC CX
		JNZ NEXT
		HLT   
CODE    ENDS
        END START