; TRANSFER 'Hello World!' TO 'HELLO WORLD!', THEN DISPLAY IT ON SCREEN 
; AND STORE THIS STRING TO THE ORIGIN ADDRESS.

DATA	SEGMENT
STRING	DB	'Hello World!'	; DEFINE THE STRING
LEN		EQU	$-STRING		; $ MEANS PRESENT ADDRESS, SUB THE BEGINNING ADDRESS OF STRING TO GET LENGTH
DATA	ENDS

CODE	SEGMENT
ASSUME	CS:CODE,DS:DATA
START:	MOV AX,DATA
		MOV DS,AX
		LEA BX,STRING		; GET THE START ADDRESS OF STRING
		MOV CL,LEN			; SET A LENGTH TIMES COUNTER
NEXT:	MOV AL,[BX]			; MOVE THE FIRST CHARACTER TO AL
		CMP AL,'a'			; COMPARE THE ASCII OF THE FIRST CHARACTER AND 'a'
		JNA	AGAINA			; IF THE THE ASCII OF THE FIRST CHARACTER IS LESS THAN 'a'S 
							; THAT MEANS THIS CHARACTER IS CAPTIAL OR A SYMBLE, JUMP TO AGAINA
		CMP AL,'z'			; OR IF THE ASCII OF THE FIRST CHARACTER IS GREAT THAN 'a', THEN 
							; COMPARE WITH 'z'
		JNA	AGAINB			; IF THE ASCII OF THE FIRST CHARACTER IS LESS THAN 'z' WHICH MEANS 
							; THIS CHARACTER IS LOWERCASE THEN JUMP TO AGAINB

AGAINA:	MOV [BX],AL			; STORE THIS CHARECTER IN ITS ORIGIN ADDRESS
		MOV DL,AL
		MOV AH,02
		INT 21H				; DISPLAY IT ON SCREEN
		INC BX				; GET NEXT CHARACTER
		DEC CL				; COUNTER--
		JNZ	NEXT			; LOOP NEXT
		HLT
		
AGAINB:	SUB AL,20H			; TURN THE LOWCASE CHARECTER TO CAPTIAL BY SUBBING THE ASCII OF 
							; THE FIRST CHARACTER 20H
		MOV [BX],AL			; STORE THE CAPTIAL ONE IN ITS ORIGIN ADDRESS
		MOV DL,AL
		MOV AH,02
		INT 21H
		INC BX
		DEC CL
		JNZ	NEXT
		HLT 
		
CODE	ENDS
		END START