; MY FIRST ASEMBLY LANGUAGE PROGRAM WITH "ASAMBLY LANGUAGE!".

DATA	SEGMENT
STRING	DB	'HELLO, ASAMBLY LANGUAGE!','$'
DATA	ENDS

CODE	SEGMENT
ASSUME	DS:DATA,ES:EXTRA,CS:CODE
START:	MOV AX,DATA
		MOV	DS,AX
		LEA DX,STRING
		MOV	AH,9
		INT	21H
		MOV	AH,4CH
		INT 21H
CODE	ENDS
		END	START
		