; THERE IS A STRING WITH 100 CHARACTERS, TEST THEM AND IF THERE IS A NUMBER(SUCH AS '1' '2' '3'...), 
; SET THE FIFTH BIT OF CL 1, OTHERWISE SET IT 0.

DATA	SEGMENT
STRING	DB	50 DUP('A'),'1',49 DUP('B')
LEN		EQU	$-STRING
DATA	ENDS

CODE	SEGMENT
ASSUME	CS:CODE,DS:DATA
START:	MOV AX,DATA
		MOV DS,AX
		MOV BX,LEN
		MOV CL,0FFH
		LEA SI,STRING
NEXT:	CMP [SI],30H
		JB	EXIT
		CMP [SI],39H
		JBE NUM
EXIT:	INC SI
		DEC BX
		JNZ NEXT 
		AND	CL,0DFH
		HLT
		
NUM:	OR	CL,20H
		HLT
;		INC SI
;		DEC BX
;		JNZ NEXT

CODE	ENDS
		END START