; TRY TO CONVERT THE HEXADECIMAL NUMBER IN AX TO ASCII CODE, AND STORE THE CORRESPONDING 
; ASCII CODE IN FOUR BYTES IN THE MEM ARRAY. FOR INSTANCE, 2449H -> '9' '4' 'A' '2'.

DATA	SEGMENT
MEM	DB	4 DUP(0)
TEM	DB	4 DUP(0)
DATA	ENDS

CODE	SEGMENT
ASSUME	CS:CODE,DS:DATA
START:	MOV AX,DATA
		MOV DS,AX
		LEA SI,MEM
		LEA DI,TEM
		MOV AX,2A49H
		MOV CX,4
CACHE:	MOV [DI],AL		; STORE EACH BIT IN TEM ARRAY
		AND	[DI],0FH
		MOV [DI+1],AL
		SHR [DI+1],CL
		MOV [DI+2],AH
		AND [DI+2],0FH
		MOV [DI+3],AH
		SHR [DI+3],CL
COMP:	CMP [DI],9		; COMPARE WITH 9, 'CAUSE THE NUMBERS GREAT THAN 9 IN HEXADECIMAL IS A B C D E F 
		JNA NUM
		ADD [DI],31H	; ASCII 'A' EQUALS TO 41H(=31H+0AH)
NEXT:	MOV	DX,[DI]		; MOVE THE NUMBERS IN TEM TO MEM
		MOV [SI],DX
		INC SI
		INC DI
		LOOP COMP
		HLT
NUM:	ADD [DI],30H
		JMP NEXT
CODE	ENDS
		END START