; SUM NUMBERS FROM 1 TO 100, THEN STORE THE RESULT IN PARAMETER S.

DATA	SEGMENT
S	DW	(0)		; (?) IN EMU8086 IS ILLEGAL
DATA	ENDS

CODE	SEGMENT
ASSUME	DS:DATA,CS:CODE
START:	MOV	AX,DATA
		MOV	DS,AX
		MOV	CX,64H
		MOV AX,0
		MOV BX,1
AGAIN:	ADD AX,BX
		INC BX
		LOOP AGAIN
		MOV S,AX
		;MOV BX,S	VERIFY THE NUMBER IN S
		MOV AH,4CH
		INT 21H
CODE	ENDS
		END	START