; WRITE A SUB-PROGRAM NESTED STRUCTURE PROGRAM MODULE, INPUT THE NAME AND 8-CHARACTER PHONE NUMBER
; THE KEYBOARD, AND DISPLAY IT IN A CERTAIN FORMAT.

DATA	SEGMENT
NAMEINPUTINFO	DB	'PLEASE INPUT NAME: $'
PHONEINPUTINFO	DB	'INPUT THE TELEPHONE NUMBER: $'
ERRORINFO		DB	0DH,0AH,'THE NUMBER YOU INPUT SHOULD BETWEEN 0-9 OR * OR # !$'
NAMEWARNINFO	DB	0DH,0AH,'LENGTH OF NAME CANNOT LONGER THAN 8 CHARACTERS!',0DH,0AH,'$'
OUTPUTINFO		DB	0DH,0AH,'NAME                    TEL',0DH,0AH,'$'
INBUF			DB	32 DUP(0)
TOTALLEN		DW	0
DATA	ENDS

STACK	SEGMENT	PARA	STACK	'STACK'
DB	100H	DUP(0)
STACK	ENDS

CODE	SEGMENT
ASSUME	DS:DATA,CS:CODE
START:	MOV AX,DATA
		MOV DS,AX
		MOV ES,AX
		CALL TELIST
		
QUIT:	MOV AH,4CH
		INT 21H
		
TELIST PROC NEAR
		MOV AH,09H
		MOV DX,OFFSET NAMEINPUTINFO
		INT 21H
		CALL INPUT_NAME
		
		MOV AH,09H
		MOV DX,OFFSET PHONEINPUTINFO
		INT 21H
		CALL INPHONE
		
		CALL PRINTLINE
		RET
TELIST	ENDP

INPUT_NAME PROC NEAR
		MOV SI,0
		MOV AH,01H
GETNAME: CMP SI,10H
		JZ	NAME_WARNING
		INT 21H
		CMP AL,0DH
		JZ	QUIT_INPUT
		MOV INBUF[SI],AL
		INC SI
		JMP GETNAME
NAME_WARNING: MOV AH,09H
		MOV DX,OFFSET NAMEWARNINFO
		INT 21H
QUIT_INPUT: MOV TOTALLEN,SI
		RET
INPUT_NAME ENDP

INPHONE PROC NEAR
		MOV SI,TOTALLEN
		MOV CX,18H				; THERE SHOULD BE 8 UNITS BETWEEN NAME STRING (16 CHARACTERS) AND 
		SUB CX,SI				; PHONE ARRAY (8 NUMBERS), BUT I WANNA FILLING ALL THE UNITS  WHICH 
FILLIN:	MOV INBUF[SI],' '				; START AFTER THE LAST CHARACTER AND END BEFORE THE FIRST NUMBER WITH 
		INC SI					; 'SPACE'.
		LOOP FILLIN
		
		MOV CX,08H
		MOV AH,01H
GETPHONE: INT 21H
		CMP AL,23H
		JZ	STORE
		CMP AL,2AH
		JZ	STORE
		CMP AL,30H
		JL	ERRORINPUT
		CMP AL,39H
		JG ERRORINPUT
STORE:	MOV INBUF[SI],AL
		INC SI
		LOOP GETPHONE
		MOV TOTALLEN,SI
		RET
ERRORINPUT: MOV AH,09H
		MOV DX,OFFSET ERRORINFO
		INT 21H
		JMP QUIT_INPUT
INPHONE	ENDP

PRINTLINE PROC NEAR
		MOV AH,09H
		MOV DX,OFFSET OUTPUTINFO
		INT 21H
		MOV SI,TOTALLEN
		MOV INBUF[SI],'$'
		MOV AH,09H
		MOV DX,OFFSET INBUF
		INT 21H
		RET
PRINTLINE ENDP

CODE	ENDS
		END	START
