; READ A BYTE OF NUMBER FROM THE PORT WHOSE ADRESS IS 3F8H, IF
; ITS BIT1 BIT3 BIT5 ARE ALL 1, THEN OUTPUT A WORD FROM DATA, 
; OTHERWISE NO WORDS OUTPUT

DATA	SEGMENT
DATA1	DW	'AB'
DATA	ENDS

CODE	SEGMENT
ASSUME	CS:CODE,DS:DATA
START:	LEA SI,DATA1
        MOV	BX,3F8H
        MOV	[BX],2AH
		MOV	DX,3F8H
WATT:	IN	AL,DX
		AND	AL,2AH
		XOR	AL,2AH
		JNZ	WATT
		MOV	DX,3F8H
		MOV	AX,[SI]
		OUT	DX,AX
CODE	ENDS
		END START
