; THERE ARE THREE WORD-NUMBERS A B C, TRY TO FIGURE OUT IF THEY ARE ABLE TO FORM A TRIANGLE,
; YES, SET CF INTO 1, OTHERWISE SET CF INTO 0.

DATA	SEGMENT
A	DW 1
B	DW 2
C	DW 2
DATA	ENDS

CODE	SEGMENT
ASSUME	CS:CODE,DS:DATA
START:	MOV AX,DATA
		MOV DS,AX
						; THE SUM OF ANY TWO SIDES OF A TRIANGLE SHOULD BE GREAT THAN THE LAST SIDE.
CASE1:	MOV AX,A
		ADD AX,B
		CMP AX,C
		JNG NOTTRI
		JMP CASE2
NOTTRI: MOV CX,0FF00H
		ADD CX,00010H
QUIT:	MOV AH,4CH
		INT 21H
CASE2:	MOV AX,B
		ADD AX,C
		CMP AX,A
		JNG NOTTRI
		MOV AX,C
		ADD AX,A
		CMP AX,B
		JNG NOTTRI
		MOV CX,0FF00H	; TO CHANGE CF INTO 1
		ADD CX,00100H
		JMP QUIT
CODE	ENDS
	END	START