; THERE IS A 8-BIT SIGNED FIGURE IN A B C RESPECTIVELY. IF ANY OF THESE THREE FIGURES IS ZERO, CLEAR A B C, 
; OTHERWISE ALL OF THEM ARE NOT ZERO, D=A+B+C.

DATA	SEGMENT
A	DB	10
B	DB	-10
C	DB	40
D	DB	0				; DEFAULT THESE VARIABLES
DATA	ENDS

CODE	SEGMENT
ASSUME	CS:CODE,DS:DATA
START:	MOV AX,DATA
		MOV DS,AX
		CMP A,0			; COMPARE A WITH ZERO
		JZ	ZERO		; IF A EQUALS TO ZERO JUMP TO ZERO
		MOV BL,A		; OTHERWISE STORE A IN BL
		CMP B,0			; COMPARE B WITH ZERO
		JZ	ZERO		; IF B IS ZERO JUMP ZERO
		ADD BL,B		; OTHERWISE BL=A+B
		CMP C,0			; COMPARE C WITH ZER0
		JZ	ZERO		; YES, JUMP TO ZERO
		ADD BL,C		; OTHERWISE BL=A+B+C
		MOV D,BL  		; STORE BL IN D
		HLT
ZERO:	MOV A,0			; CLEAR A B C
		MOV B,0
		MOV C,0  
		HLT
CODE	ENDS
		END START